# Example config file

in_files_dir: "/home/tomas/tier4/control_analysis_pipeline/input_files"
save_preprocessed_files_dir: "/home/tomas/tier4/control_analysis_pipeline/preprocessed_files"
load_preprocessed_files_dir: "/home/tomas/tier4/control_analysis_pipeline/preprocessed_files"

resampling_period: 0.03 # sampling period that should be used when resampling the data
minimum_signal_length: 10.0 # seconds
discard_after_enable: 2.0


data_to_load:
  steer_status:
    topic: "/vehicle/status/actuation_status"
    var: "status.steer_status"
    type: "output"
  steer_cmd:
    topic: "/control/command/actuation_cmd"
    var: "actuation.steer_cmd"
    type: "input"
  pacmode_enabled:
    topic: "/pacmod/enabled"
    var: "data"
    type: "enable"
  aw_enabled:
    topic: "/control/vehicle_cmd_gate/operation_mode"
    var: "is_autoware_control_enabled"
    type: "enable"
  speed_filter:
    topic: "/pacmod/vehicle_speed_rpt"
    var: "vehicle_speed"
    type: "filtering"
    operator: "gt"  # gt, lt, eq, ge, le
    val: 2.0

